### ISSUE TITLE
Minor announcer bug

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#1]
The person who says the gametype name "Sabotage" says sabotage twice at the start of the first round of the match of any map.
In this timeframe you can walk around in black and white mode, (Where player is supposed to remain temporaily frozen)

**Comment by Daxy7** [comment]
After about 5-7 or so maps were finished in the same session, the MOTD doesn't appear but it still lets you join.
I would like if viewing MOTD for the first time, on the second map the MOTD won't appear anymore. 
(Similar thing this bug does but sooner)

**Comment by upl1nk-v01d** [comment]
> 

This should be as expected, because variable 'filename' changed according to server's local date format.
The log files are stored like yyyy-mm-dd.log format. The filename variable '2022-06-25' changed to '2022-06-26' and on server there was no such file 'motd/2022-06-25.log' to read.
Please see https://github.com/upl1nk-v01d/cod4x_v01d_mod/blob/main/scripts/menus.gsc thread _get_motd_txt().

**Comment by upl1nk-v01d** [comment]
Fixed player controls in prematch timeframe.
Please see https://github.com/upl1nk-v01d/cod4x_v01d_mod/blob/main/scripts/main.gsc thread _prematch().
Not sure about sab dialog double announcement.

**Comment by Daxy7** [comment]
Closed: Sabotage double dialog fixed by code changes.
